name: Feature Request
description: Suggest a new feature or enhancement for FinFlow
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this affect?
      options:
        - Backend API
        - Frontend UI
        - Database Schema
        - Authentication
        - Statement Processing
        - Google Sheets Integration
        - Custom Tables
        - Telegram Bot
        - Docker Setup
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Very important
        - Medium - Would be nice to have
        - Low - Not urgent
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how you would use this feature
      placeholder: |
        As a [type of user], I want to [do something] so that [achieve some goal].
        
        Example scenarios:
        1. When I...
        2. I need to...
        3. This would help me...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or links to similar features in other applications
      placeholder: You can drag and drop images here or paste links

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details (Optional)
      description: If you have technical suggestions on how to implement this, please share
      placeholder: |
        This could be implemented by...
        Required changes:
        - API endpoint: ...
        - Database: ...
        - UI component: ...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any other information that might be helpful...

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with FinFlow's goals
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
